my:
  datasource:
    url: local.db.com
    username: local_user
    password: local_pw
    etc:
      max-connection: 1
      timeout: 60s
      options: LOCAL, CACHE


# application.properties와 application.yml을 같이 사용하면 properties가 우선권을 가진다.
# 하지만 둘이 같이 사용하는 일이 없다.
# 실무에서는 설정 정보가 많아서 보기 편한 yml을 선호한다.


---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username: dev_user
    password: dev_pw
    etc:
      max-connection: 1
      timeout: 60s
      options: DEV, CACHE
---
spring:
  config:
    activate:
      on-profile: prod
my:
  datasource:
    url: prod.db.com
    username: prod_user
    password: prod_pw
    etc:
      max-connection: 1
      timeout: 60s
      options: PROD, CACHE